name: Deploy to HF Spaces

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config user.email "ci@finapi.dev"
          git config user.name "CI"
          git push https://rihemfinance:$HF_TOKEN@huggingface.co/spaces/rihemfinance/finsentiment main